--STORED PROCEDURE

CREATE PROCEDURE STAR_INSERT 
AS
BEGIN


	--REMOVE CONSTRAINTS FROM STAR SCHEMA TABLES
	ALTER TABLE STAR_CUSTOMER
	DROP CONSTRAINT PK_STAR_CUSTOMER

	ALTER TABLE STAR_EMPLOYEE
	DROP CONSTRAINT PK_STAR_EMPLOYEE

	ALTER TABLE STAR_DEPARTMENT
	DROP CONSTRAINT PK_STAR_DEPARTMENT

	ALTER TABLE STAR_PRODUCT
	DROP CONSTRAINT PK_STAR_PRODUCT

	ALTER TABLE STAR_TIME
	DROP CONSTRAINT PK_STAR_TIME

	ALTER TABLE STAR_FACT
	DROP CONSTRAINT PK_1_STAR_FACT,
		 CONSTRAINT FK_1_STAR_FACT,
		 CONSTRAINT FK_2_STAR_FACT,
		 CONSTRAINT FK_3_STAR_FACT,
		 CONSTRAINT FK_4_STAR_FACT,
		 CONSTRAINT FK_5_STAR_FACT


	--TRUNCATE STAR SCHEMA TABLES
	TRUNCATE TABLE STAR_CUSTOMER
	TRUNCATE TABLE STAR_EMPLOYEE
	TRUNCATE TABLE STAR_DEPARTMENT
	TRUNCATE TABLE STAR_PRODUCT
	TRUNCATE TABLE STAR_TIME
	TRUNCATE TABLE STAR_FACT

	

    -- INSERT STATEMENTS FOR PROCEDURE HERE
	
		INSERT INTO STAR_CUSTOMER
		(CUST_CODE, CUST_FNAME, CUST_LNAME, CUST_STREET, CUST_CITY, CUST_STATE, CUST_ZIP, CUST_BALANCE)
		SELECT *
		FROM LGCUSTOMER


		INSERT INTO STAR_EMPLOYEE
		(EMP_NUM, EMP_FNAME, EMP_LNAME, EMP_EMAIL, EMP_PHONE, EMP_HIREDATE, EMP_TITLE, EMP_COMM, DEPT_NUM)
		SELECT *
		FROM LGEMPLOYEE


		INSERT INTO STAR_DEPARTMENT
		(DEPT_NUM, DEPT_NAME, DEPT_MAIL_BOX, DEPT_PHONE, EMP_NUM)
		SELECT *
		FROM LGDEPARTMENT

	
		INSERT INTO STAR_PRODUCT
		(PROD_SKU, PROD_DESCRIPT, PROD_TYPE, PROD_BASE, PROD_CATEGORY, PROD_PRICE, PROD_QOH, PROD_MIN, BRAND_ID)
		SELECT *
		FROM LGPRODUCT

	
		INSERT INTO STAR_TIME
		(INV_DATE, INV_YEAR, INV_MONTH)
		SELECT INV_DATE, YEAR(INV_DATE) AS INV_YEAR, MONTH(INV_DATE) AS INV_MONTH
		FROM LGINVOICE
	
	

	--ADDING THE CONSTRAINTS BACK TO THE TABLES
	ALTER TABLE STAR_CUSTOMER
	ADD CONSTRAINT PK_STAR_CUSTOMER PRIMARY KEY(CUST_ID)

	ALTER TABLE STAR_EMPLOYEE
	ADD CONSTRAINT PK_STAR_EMPLOYEE PRIMARY KEY(EMP_ID)

	ALTER TABLE STAR_PRODUCT
	ADD CONSTRAINT PK_STAR_PRODUCT PRIMARY KEY(PROD_ID)

	ALTER TABLE STAR_DEPARTMENT
	ADD CONSTRAINT PK_STAR_DEPARTMENT PRIMARY KEY(DEPT_ID)

	ALTER TABLE STAR_TIME
	ADD CONSTRAINT PK_STAR_TIME PRIMARY KEY(TIME_ID)

	ALTER TABLE STAR_FACT
	ADD CONSTRAINT PK_1_STAR_FACT PRIMARY KEY(CUST_ID, EMP_ID, DEPT_ID, PROD_ID, TIME_ID),
		CONSTRAINT FK_1_STAR_FACT FOREIGN KEY(CUST_ID)REFERENCES STAR_CUSTOMER,
		CONSTRAINT FK_2_STAR_FACT FOREIGN KEY(EMP_ID)REFERENCES STAR_EMPLOYEE,
		CONSTRAINT FK_3_STAR_FACT FOREIGN KEY(DEPT_ID)REFERENCES STAR_DEPARTMENT,
		CONSTRAINT FK_4_STAR_FACT FOREIGN KEY(PROD_ID)REFERENCES STAR_PRODUCT,
		CONSTRAINT FK_5_STAR_FACT FOREIGN KEY(TIME_ID)REFERENCES STAR_TIME

	
END
GO

--CREATE STAGING TABLE
  CREATE TABLE STAR_STAGING
	(
	CUST_ID INT NOT NULL,
	EMP_ID INT NOT NULL,
	DEPT_ID INT NOT NULL,
	PROD_ID INT NOT NULL,
	TIME_ID INT NOT NULL,
	CUST_CODE INT NOT NULL,
	EMP_NUM INT NOT NULL,
	DEPT_NUM INT NOT NULL,
	PROD_SKU NVARCHAR(15) NOT NULL,
	INV_DATE DATETIME NOT NULL,
	LINE_QTY FLOAT,
	LINE_PRICE DECIMAL(8,2)
	)


--INSERT STATEMENTS TO POPULATE STAGING TABLE
		INSERT INTO STAR_STAGING
		(CUST_CODE, EMP_NUM, DEPT_NUM, PROD_SKU, INV_DATE, LINE_QTY, LINE_PRICE)
		SELECT C.CUST_CODE, E.EMP_NUM, D.DEPT_NUM, P.PROD_SKU, I.INV_DATE, LINE_QTY, LINE_PRICE
		FROM LGCUSTOMER C INNER JOIN LGINVOICE I ON C.CUST_CODE = I.CUST_CODE
							INNER JOIN LGLINE L ON I.INV_NUM = L.INV_NUM
							INNER JOIN LGPRODUCT P ON L.PROD_SKU = P.PROD_SKU
							INNER JOIN LGEMPLOYEE E ON I.EMPLOYEE_ID = E.EMP_NUM
							INNER JOIN LGDEPARTMENT D ON E.DEPT_NUM = D.DEPT_NUM 
		


--ASSIGNING DATA WAREHOUSE KEYS TO STAGING TABLE
		UPDATE STAR_STAGING
		SET CUST_ID = C.CUST_ID
		FROM STAR_STAGING S INNER JOIN STAR_CUSTOMER C
				ON S.CUST_CODE = C.CUST_CODE

		UPDATE STAR_STAGING
		SET EMP_ID = E.EMP_ID
		FROM STAR_STAGING S INNER JOIN STAR_EMPLOYEE E
				ON S.EMP_NUM = E.EMP_NUM

		UPDATE STAR_STAGING
		SET DEPT_ID = D.DEPT_ID
		FROM STAR_STAGING S INNER JOIN STAR_DEPARTMENT D
				ON S.DEPT_NUM = D.DEPT_NUM

		UPDATE STAR_STAGING
		SET PROD_ID = P.PROD_ID
		FROM STAR_STAGING S INNER JOIN STAR_PRODUCT P
				ON S.PROD_SKU = P.PROD_SKU

		UPDATE STAR_STAGING
		SET TIME_ID = T.TIME_ID
		FROM STAR_STAGING S INNER JOIN STAR_TIME T
				ON S.INV_DATE = T.INV_DATE


--POPULATE FACT TABLE WITH STAGING TABLE
		INSERT INTO STAR_FACT
		(CUST_ID, EMP_ID, DEPT_ID, PROD_ID, TIME_ID, LINE_QTY, LINE_PRICE)
		SELECT CUST_ID, EMP_ID, DEPT_ID, PROD_ID, TIME_ID, LINE_QTY, LINE_PRICE
		FROM STAR_STAGING 