--ASSIGNMENT 10

DROP TABLE STAR_CUSTOMER
DROP TABLE STAR_EMPLOYEE
DROP TABLE STAR_PRODUCT
DROP TABLE STAR_DEPARTMENT
DROP TABLE STAR_TIME
DROP TABLE STAR_FACT
--CREATING THE TABLES
CREATE TABLE STAR_CUSTOMER
	(
	CUST_ID INT IDENTITY NOT NULL,
	CUST_CODE INT NOT NULL,
	CUST_FNAME NVARCHAR(20),
	CUST_LNAME NVARCHAR(20),
	CUST_STREET NVARCHAR(70),
	CUST_CITY NVARCHAR(50),
	CUST_STATE NVARCHAR(2),
	CUST_ZIP NVARCHAR(5),
	CUST_BALANCE DECIMAL(8,2)
	)

CREATE TABLE STAR_EMPLOYEE
	(
	EMP_ID INT IDENTITY NOT NULL,
	EMP_NUM INT NOT NULL,
	EMP_FNAME NVARCHAR(20),
	EMP_LNAME NVARCHAR(25),
	EMP_EMAIL NVARCHAR(25),
	EMP_PHONE NVARCHAR(20),
	EMP_HIREDATE DATETIME,
	EMP_TITLE NVARCHAR(45),
	EMP_COMM DECIMAL(2,2),
	DEPT_NUM INT
	)

CREATE TABLE STAR_PRODUCT
	(
	PROD_ID INT IDENTITY NOT NULL,
	PROD_SKU NVARCHAR(15) NOT NULL,
	PROD_DESCRIPT NVARCHAR(255),
	PROD_TYPE NVARCHAR(255),
	PROD_BASE NVARCHAR(255),
	PROD_CATEGORY NVARCHAR(255),
	PROD_PRICE DECIMAL(10,2),
	PROD_QOH DECIMAL(10,0),
	PROD_MIN DECIMAL(10,0),
	BRAND_ID INT
	)

CREATE TABLE STAR_DEPARTMENT
	(
	DEPT_ID INT IDENTITY NOT NULL,
	DEPT_NUM INT NOT NULL,
	DEPT_NAME NVARCHAR(50),
	DEPT_MAIL_BOX NVARCHAR(3),
	DEPT_PHONE NVARCHAR(9),
	EMP_NUM INT
	)

CREATE TABLE STAR_TIME
	(
	TIME_ID INT IDENTITY NOT NULL,
	INV_DATE DATETIME NOT NULL,
	INV_YEAR INT,
	INV_MONTH INT
	)

CREATE TABLE STAR_FACT
	(
	CUST_ID INT NOT NULL,
	EMP_ID INT NOT NULL,
	DEPT_ID INT NOT NULL,
	PROD_ID INT NOT NULL,
	TIME_ID INT NOT NULL,
	LINE_QTY FLOAT,
	LINE_PRICE DECIMAL(8,2)
	)

--ALTERING THE TABLES/ADDING CONSTRAINTS
ALTER TABLE STAR_CUSTOMER
ADD CONSTRAINT PK_STAR_CUSTOMER PRIMARY KEY(CUST_ID)

ALTER TABLE STAR_EMPLOYEE
ADD CONSTRAINT PK_STAR_EMPLOYEE PRIMARY KEY(EMP_ID)

ALTER TABLE STAR_PRODUCT
ADD CONSTRAINT PK_STAR_PRODUCT PRIMARY KEY(PROD_ID)

ALTER TABLE STAR_DEPARTMENT
ADD CONSTRAINT PK_STAR_DEPARTMENT PRIMARY KEY(DEPT_ID)

ALTER TABLE STAR_TIME
ADD CONSTRAINT PK_STAR_TIME PRIMARY KEY(TIME_ID)

ALTER TABLE STAR_FACT
ADD CONSTRAINT PK_1_STAR_FACT PRIMARY KEY(CUST_ID, EMP_ID, DEPT_ID, PROD_ID, TIME_ID),
	CONSTRAINT FK_1_STAR_FACT FOREIGN KEY(CUST_ID)REFERENCES STAR_CUSTOMER,
	CONSTRAINT FK_2_STAR_FACT FOREIGN KEY(EMP_ID)REFERENCES STAR_EMPLOYEE,
	CONSTRAINT FK_3_STAR_FACT FOREIGN KEY(DEPT_ID)REFERENCES STAR_DEPARTMENT,
	CONSTRAINT FK_4_STAR_FACT FOREIGN KEY(PROD_ID)REFERENCES STAR_PRODUCT,
	CONSTRAINT FK_5_STAR_FACT FOREIGN KEY(TIME_ID)REFERENCES STAR_TIME

--TESTING THE DATABASE

--1
SELECT CUST_CITY AS CITY, PRODUCT_CATEGORY AS CATEGORY, 
FROM STAR_FACT
HAVING (LINE_QTY * LINE_PRICE)

--2
SELECT INV_MONTH
FROM STAR_FACT
HAVING MAX(LINE_QTY * LINE_PRICE)

--3: FIND THE HIGHEST ORDERLINE PRICE AND DISPLAY THAT ORDER'S PROD_SKU, CUSTOMER BY CUST_CODE, DATE PURCHASED ALONG WITH THE EMPLOYEE LAST NAME, 
--   THEIR DEPARTMENT NUM.  
SELECT EMP_LNAME, DEPT_NUM, CUST_CODE, INV_DATE, PROD_SKU
FROM STAR_FACT
HAVING MAX(LINE_PRICE)