SELECT *
FROM LGLINE

SELECT *
FROM LGPRODUCT


--CODE TO TEST THE TRIGGER
SELECT PROD_SKU, COUNT(*)
FROM LGLINE
GROUP BY PROD_SKU
ORDER BY PROD_SKU


SELECT PROD_SKU, PROD_QOH
FROM LGPRODUCT
WHERE PROD_SKU IN ('3561-LYU','9702-WFX','6933-YOI')


--INSERT TEST
INSERT INTO LGLINE
VALUES (3452, 3, '3561-LYU', 6, NULL)


--DELETE TEST
DELETE FROM LGLINE
WHERE INV_NUM = 3452


--UPDATE TESTS
UPDATE LGLINE
SET LINE_QTY = LINE_QTY - 5
WHERE PROD_SKU = '3561-LYU' OR
	  LINE_NUM = 6

UPDATE LGLINE 
SET LINE_QTY = LINE_QTY + 5
WHERE PROD_SKU = '3561-LYU' OR
	  LINE_NUM = 6




--THE TRIGGER
CREATE TRIGGER NEW_QUANTITY_ON_HAND
	ON LGLINE
	AFTER INSERT, DELETE, UPDATE 
AS 
BEGIN

		DECLARE @PROD_SKU CHAR(8)
		DECLARE @NEW_TOTAL INT


   
   IF(EXISTS(SELECT * 
			 FROM inserted))
	BEGIN
			DECLARE INSERTED_CURSOR CURSOR FOR
			SELECT PROD_SKU, SUM(LINE_QTY) AS NEW_TOTAL
			FROM inserted
			GROUP BY PROD_SKU

			OPEN INSERTED_CURSOR
			FETCH NEXT FROM INSERTED_CURSOR
				  INTO @PROD_SKU, @NEW_TOTAL
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
				UPDATE LGPRODUCT
				SET PROD_QOH = PROD_QOH - @NEW_TOTAL
				WHERE PROD_SKU = @PROD_SKU
				FETCH NEXT FROM INSERTED_CURSOR
					  INTO @PROD_SKU, @NEW_TOTAL
			END 
			CLOSE INSERTED_CURSOR
			DEALLOCATE INSERTED_CURSOR
	END


	IF(EXISTS(SELECT * 
			 FROM deleted))
	BEGIN
			DECLARE DELETED_CURSOR CURSOR FOR
			SELECT PROD_SKU, SUM(LINE_QTY) AS NEW_TOTAL
			FROM deleted
			GROUP BY PROD_SKU

			OPEN DELETED_CURSOR
			FETCH NEXT FROM DELETED_CURSOR
				  INTO @PROD_SKU, @NEW_TOTAL
			WHILE(@@FETCH_STATUS = 0)
			BEGIN
				UPDATE LGPRODUCT
				SET PROD_QOH = PROD_QOH + @NEW_TOTAL
				WHERE PROD_SKU = @PROD_SKU
				FETCH NEXT FROM DELETED_CURSOR
					  INTO @PROD_SKU, @NEW_TOTAL
			END 
			CLOSE DELETED_CURSOR
			DEALLOCATE DELETED_CURSOR
	END
   
END
GO


